DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS messages;
DROP TABLE IF EXISTS conversations;
DROP TABLE IF EXISTS queue;
DROP TABLE IF EXISTS logs;

DROP TYPE IF EXISTS source_type;
DROP TYPE IF EXISTS incident_type;